
name: Regression tests
on:   [workflow_dispatch]

env:
   installDir: ${{ github.workspace }}/coriolis-2.x/Linux.x86_64/Release.Shared/install

jobs:
  Regression-Tests:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         submodules: true
         path:       coriolis-2.x/src/core-v-180-mcu
     - uses: actions/checkout@v3
       with:
         repository: lip6/coriolis
         submodules: true
         path:       coriolis-2.x/src/coriolis
     - uses: actions/checkout@v3
       with:
         repository: lip6/alliance
         path:       coriolis-2.x/src/alliance
     - uses: actions/checkout@v3
       with:
         repository: lip6/alliance-check-toolkit
         path:       coriolis-2.x/src/alliance-check-toolkit
     - uses: actions/checkout@v3
       with:
         repository: YosysHQ/yosys
         path:       coriolis-2.x/src/yosys
         ref:        yosys-0.24
     - uses: actions/checkout@v3
       with:
         repository: zachjs/sv2v
         path:       coriolis-2.x/src/sv2v
     - name: Update APT cache
       run: sudo apt-get update
     - name: Install software dependencies
       run: >
         sudo apt-get install libboost-all-dev rapidjson-dev \
                              python-dev-is-python3 python3-doit \
                              qtbase5-dev qtbase5-dev-tools libqt5svg5-dev libqwt-qt5-dev \
                              libeigen3-dev liblemon-dev \
                              autotools-dev automake \
                              libxt-dev libxpm-dev libmotif-dev \
                              tcl-dev libffi-dev haskell-stack
     - name: ccache
       uses: hendrikmuhs/ccache-action@v1.2
     - name: Build sv2v
       run: |
         export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
         cd ${{ github.workspace }}/coriolis-2.x/src/sv2v
         make
         mkdir -p ${{ env.installDir }}/bin
         cp ./bin/sv2v ${{ env.installDir }}/bin
     - name: Build Yosys
       run: |
         export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
         cd ${{ github.workspace }}/coriolis-2.x/src/yosys
         make ENABLE_PYOSYS=1 config-gcc
         make ENABLE_PYOSYS=1 \
              PREFIX=${{ env.installDir }} \
              PYTHON_DESTDIR=${{ env.installDir }}/lib64/python3/dist-packages \
              LIBDIR=${{ env.installDir }}/lib64/yosys \
              DATDIR=${{ env.installDir }}/share/yosys \
              install
         sudo ln -s ${{ env.installDir }}/bin/* /usr/bin/
     - name: Check Yosys share directory
       run: ls -1 ${{ github.workspace }}/coriolis-2.x/Linux.x86_64/Release.Shared/install/share/yosys
    #- name: Build Alliance
    #  run: |
    #    export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
    #    ${{ github.workspace }}/coriolis-2.x/src/coriolis/bootstrap/allianceInstaller.sh --github-runner=${{ github.workspace }}
     - name: Build Coriolis
       run: |
         export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
         ${{ github.workspace }}/coriolis-2.x/src/coriolis/bootstrap/ccb.py --root=${{ github.workspace }}/coriolis-2.x --project=coriolis --make="-j4 install"
     - name: Check for binaries
       run: ls -1 ${{ github.workspace }}/coriolis-2.x/Linux.x86_64/Release.Shared/install/bin
     - name: Build the layout of cv32e40p
       run: |
         export CORIOLIS_TOP=${{ env.installDir }}
         cd ${{ github.workspace }}/coriolis-2.x/src/core-v-180-mcu/coriolis
         ../../alliance-check-toolkit/bin/crlenv.py --verbose
         ../../alliance-check-toolkit/bin/crlenv.py -- doit pnr
#    - name: Bundle installed tree
#      uses: actions/upload-artifact@v3
#      with:
#        name: installed-tree
#        path: ${{ github.workspace }}/coriolis-2.x/Linux.x86_64/Release.Shared/install
#        retention-days: 1
     - name: Archive test design set logs
       uses: actions/upload-artifact@v3
       with:
         name: cv32e40p-gds
         path: ${{ github.workspace }}/coriolis-2.x/src/core-v-180-mcu/coriolis/cv32e40p_core_cts_r.gds
         retention-days: 5
